build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Grafana Cloud"
  org.opencontainers.image.description: "Grafana Cloud Addon."
  org.opencontainers.image.source: "https://github.com/grafana/home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  AGENT_VERSION: "v0.39.1"
