name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 🔍 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@a7c616ce81ccda50150bf1595786c71b1883fabb # master

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@de232482c564942a796a4427d3624f0d6c6e36e8 # v2.16
        with:
          path: "./${{ matrix.path }}"
